### PR TITLE
Displays a message on key press. Fixes #9

### LINKED ISSUE #9: Display the message when the button is pressed
Since sometimes the presentation is displayed with delays (because of the big size) it's confusing for the presenter sometimes because when they use clicker, they don't know if the clicker didn't work (especially the infrared ones) or it's the delay within OpenSlides when it's trying to load the mediafile.

My proposal is to add some kind of message that would show that some button was pressed, so it would be more clear.

(again, this is mostly for me, since I'm gonna make a PR on it, but I'm interested in your opinion @lesteenman, what do you think about it?)

### PR DESCRIPTION
**Pull request by serge1peshcoff**
Self-explanatory.
If more comments or improvements are required, any feedback is appreciated ;)

### CODE REVIEW

**Comment by serge1peshcoff** [comment]
I've added messages for:
- keypresses when something is done (e.g. going to next/previous slide, restarting presentation etc.)
- keypresses when the action cannot be done (e.g. going from slide 1 to 0)
- keypresses when media is not controllable

and also I've put myself into the contributors list, if you don't mind :D

**Comment by i3anaan** [comment]
Looks good to me!

**Comment by lesteenman** [comment]
Is using '...' after sentences something OpenSlides does in other places as well? Otherwise, I would suggest to stick to the style of other messages, which I assume (based on the screenshot you sent earlier) to just use a single period after a sentence.

Is there a particular reason you want to show what key is actually pressed? I think in most cases, this does not add any value, apart from more text on screen. Furthermore, it can be confusing, as a presentation remote simulates other key presses, so the message would be wrong in what I assume is a common use case.

Finally, I would say something like "Already at first slide." instead of "Cannot go to first slide". Maybe both messages, but I personally think you need to add the reason to the 'error' message. This last point is just a personal preference though, I think, so I would like to hear your opinions on it.

**Comment by serge1peshcoff** [comment]
@lesteenman 
1) my idea was to display triple dots on the cases when the action is done, and single dot when action cannot be done (e.g. going to slide 0 etc.) I didn't look at how it is used in OpenSlides itself, but if it is the way you described, then it's reasonable to do it the OpenSlides way. Maybe @FinnStutzenstein or somebody from the OpenSlides core developers can elaborate on that?
2) actually no particular reason, but IMO it can be useful for debugging and getting the full idea on what was pressed. Btw, the keycode inside the message would be displayed only if some action can be done by pressing this button, otherwise nothing would be displayed.
3) that makes sense, I love your option more than mine. Will implement that tomorrow.

Thanks for the feedback ;)

**Comment by serge1peshcoff** [comment]
@lesteenman I've got another idea that I think is worth adding.
OpenSlides allows displaying different messages types, they will be displayed with different colors (like in Bootstrap, I suppose: https://www.w3schools.com/bootstrap/bootstrap_alerts.asp).
I've marked them as `warning` because this is the first thing I've found (I've used the server disconnect message as a result), but since there's a possibility to mark them in the different way, I think it'd be cool to display the success messages as `info` (I think it would be more suitable than `success` here) and error messages (e.g. 'Already at the first slide') as `danger`. What do you think?

**Comment by lesteenman** [comment]
Different colors sound good to me. I think danger is a bit too 'aggressive' for being at the first slide though. Warning sounds like a proper level to note that an action can not be performed, as it is not _a dangerous or potentially negative action_. I have no strong feelings between using `info` or `success` for successfully changing slides. While you could say it is a successful action, it's also just informative, and not particularly positive.

A second opinion from actual developers on the consistency for the messaging would be nice. However, looking at the messages that are already in use, the consistency seems to be that actions that are still in progress use triple periods (e.g. _Generating PDF file..._), while completed actions use a single period (_PDF successfully generated._). This feels like natural use of punctuation to me as well, so I would advocate for single periods in this case.

**Comment by serge1peshcoff** [comment]
@lesteenman another triple/single dots thought: I totally agree with your point, but counting the delay OpenSlides add while switching slides (especially when the presentation is big, it takes quite a long time, up to 5 seconds) and since switching slides is not instant, that can also be counted as the action in progress, what do you think?
About color scheme, I agree with you that it should be warning instead of error, that really makes sense.

**Comment by lesteenman** [comment]
That's also a fair point. I would still prefer not to show the key presses, or somehow add them more subtly to the message, so you can easily skim the message and see what's actually going to happen/happening.

**Comment by serge1peshcoff** [comment]
@lesteenman do you have any ideas on how we can leave the key presses there and also make it more subtle?

**Comment by lesteenman** [comment]
Perhaps on another line, italic? Then you can still easily skim the line saying what's happening, which IMO is the important information.

**Comment by serge1peshcoff** [comment]
@lesteenman like that?
image

**Comment by serge1peshcoff** [comment]
@lesteenman looks even better if the font size of the 2nd line is decreased, like that:

image

**Comment by lesteenman** [comment]
Looks good to me! I didn't expect you could set font sizes.

**Comment by serge1peshcoff** [comment]
@lesteenman you can insert any HTML markup there :D
Also regarding what you've wrote in the issue, I've set the message time to 2s, and every new message would overwrite the existing one, so the user won't end up with screen full of messages because the person with the clicker pressed a lot of buttons.

**Comment by lesteenman** [comment]
Yes, I noticed that. I think that's fine, although 2 seconds might be a
*bit* short. That's a matter of feeling, though.

**Comment by serge1peshcoff** [comment]
@lesteenman so other than that I think it's finished, can we merge it then?

**Comment by lesteenman** [comment]
Yeah. I had missed you had already made a new commit.

**Pull request merged**
