### PR TITLE
Added preview and unlocked OS version

### PR DESCRIPTION
**Pull request by FinnStutzenstein**

### CODE REVIEW

**Comment by lesteenman** [comment]
Looking into the comment thread, it seems this has been tested and is working. Correct?

**Comment by FinnStutzenstein** [comment]
@serge1peshcoff @i3anaan may tell about the iframe. I tested this plugin with OS 2.2b3 and it works fine, so the removal of the upper version limit is ok.

**Comment by lesteenman** [comment]
I believe I've seen the frame in action before. While I would prefer something that looks/feels a bit more elegant, this is definitely an improvement over not having anything.

**Comment by serge1peshcoff** [comment]
I will re-check it in an hour if it's working, but thanks improving it anyway ;)

**Comment by serge1peshcoff** [comment]
@FinnStutzenstein can you change the `iframe`'s `src` from `/projector` to `/projector/1`? because for me it displays the main page instead of actual projector.
otherwise, looks really cool, thanks!

**Comment by lesteenman** [comment]
There is support for multiple projectors in OpenSlides now, right? I think there should be support for that as well, by selecting the active projector in a dropdown, just like the live preview in the sidebar does. For now, though, just always going for projector 1 is probably the right move.

**Comment by FinnStutzenstein** [comment]
Yes this should be faily ease, just look at the code for the projector sidebar. Also projectors can have different aspect ratios than 3:4. The projector preview also resizes the iframe to the correct ratio, too.

**Comment by lesteenman** [comment]
Please see the related issues.

**Pull request merged**
